### Оплата товаров клиента по его id
POST localhost:8080/client/2/transfer


### Создание аккаунта
POST localhost:8080/account
Content-Type: application/json

{
  "clientId": 2,
  "balance": 200
}

### Получение списка аккаунтов
GET localhost:8080/account
