### Добавление продукта в корзину
POST localhost:8080/carts/7/products/5

### Изменение количества продукта в корзине
PATCH localhost:8080/carts/7/products/5
Content-Type: application/json

{
  "productCount": 1
}

### Удаление продукта из корзины
DELETE localhost:8080/carts/7/products/5


### Создание корзины
POST localhost:8080/carts
Content-Type: application/json

{
  "promoCode": "1xBet"
}

### Получение корзины по ее id (в подробном виде)
GET localhost:8080/carts/7

### Получение всех корзин (как строки в БД)
GET localhost:8080/carts

### Изменение корзины по ее id
PUT localhost:8080/carts/7
Content-Type: application/json

{
  "promoCode": "1xСтавка"
}

### Удаление корзины по ее id
DELETE localhost:8080/carts/1
