### Добавление продукта в корзину
PATCH localhost:8080/cart/add
Content-Type: application/json

{
  "cartId": 3,
  "productId": 2
}

### Изменение количества продукта в корзине
PATCH localhost:8080/cart/change
Content-Type: application/json

{
  "cartId": 3,
  "productId": 2,
  "productCount": 5
}

### Удаление продукта из корзины
DELETE localhost:8080/cart
Content-Type: application/json

{
  "cartId": 2,
  "productId": 2
}


### Создание корзины
POST localhost:8080/cart
Content-Type: application/json

{
  "promoCode": "1xBet"
}

### Получение корзины по ее id
GET localhost:8080/cart/3

### Получение всех корзин
GET localhost:8080/cart

### Изменение корзины
PUT localhost:8080/cart
Content-Type: application/json

{
  "id": 3,
  "promoCode": "1xСтавка"
}

### Удаление корзины по ее id
DELETE localhost:8080/cart/1
