### Добавление продукта в корзину
PATCH localhost:8080/cart/add
Content-Type: application/json

{
  "cartId": 7,
  "productId": 5
}

### Изменение количества продукта в корзине
PATCH localhost:8080/cart/change
Content-Type: application/json

{
  "cartId": 7,
  "productId": 5,
  "productCount": 1
}

### Удаление продукта из корзины
DELETE localhost:8080/cart
Content-Type: application/json

{
  "cartId": 5,
  "productId": 5
}


### Создание корзины
POST localhost:8080/cart
Content-Type: application/json

{
  "promoCode": "1xBet"
}

### Получение корзины по ее id (в подробном виде)
GET localhost:8080/cart/7

### Получение всех корзин (как строки в БД)
GET localhost:8080/cart

### Изменение корзины
PUT localhost:8080/cart
Content-Type: application/json

{
  "id": 7,
  "promoCode": "1xСтавка"
}

### Удаление корзины по ее id
DELETE localhost:8080/cart/1
