### Создание клиента
POST localhost:8080/client
Content-Type: application/json

{
  "name": "Илья",
  "email": "i1@yandex.ru",
  "login": "i1",
  "password": "1xBet"
}

### Получение клиента по его id
GET localhost:8080/client/1

### Удаление клиента по его id
DELETE localhost:8080/client/1
