### Создание продукта
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Душа",
  "price": 200,
  "count": 5
}

### Получение продукта по его id
GET localhost:8080/products/5

### Получение всех продуктов
GET localhost:8080/products

### Получение продуктов по подстроке наименования
GET localhost:8080/products?name=Душ

### Изменение продукта по его id
PUT localhost:8080/products/5
Content-Type: application/json

{
  "name": "Морковь",
  "price": 35,
  "count": 10
}

### Удаление продукта по его id
DELETE localhost:8080/products/6
