### Создание продукта
POST localhost:8080/product
Content-Type: application/json

{
  "name": "Душа",
  "price": 200,
  "count": 5
}

### Получение продукта по его id
GET localhost:8080/product/3

### Получение всех продуктов
GET localhost:8080/product

### Получение продуктов по подстроке наименования
GET localhost:8080/product?name=Душ

### Изменение продукта
PUT localhost:8080/product
Content-Type: application/json

{
  "id": 3,
  "name": "Морковь",
  "price": 35,
  "count": 10
}

### Удаление продукта по его id
DELETE localhost:8080/product/4
