###
# Добавление нового продукта
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Яблоко",
  "price": 35,
  "countInStore": 5
}

###
# Получение списка всех продуктов
GET localhost:8080/products

###
# Получение продукта по его id
GET localhost:8080/products/1

###
# Изменение продукта по его id
PUT localhost:8080/products/3
Content-Type: application/json

{
  "name": "Груша",
  "price": 70,
  "countInStore": 3
}

###
# Удаление продукта по его id
DELETE localhost:8080/products/1
