###
# Регистрация нового клиента
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Илья",
  "email": "i1@ya.ru",
  "login": "i1ya",
  "password": "57r0n9"
}

###
# Получение списка всех клиентов
GET localhost:8080/users

###
# Получение клиента по его id
GET localhost:8080/users/1

###
# Изменение клиента по его id
PUT localhost:8080/users/1
Content-Type: application/json

{
  "name": "неКирилл",
  "email": "k1@gmail.com",
  "login": "k1r111",
  "password": "n0757r0n9"
}


###
# Добавление одной единицы продукта клиенту по id продукта
POST localhost:8080/users/7/cart/products
Content-Type: application/json

{
  "id": 3
}

###
# Получение списка всех продуктов у клиента
GET localhost:8080/users/7/cart/products

###
# Изменение количества продукта у клиента
PUT localhost:8080/users/1/cart/products/3
Content-Type: application/json

{
  "productCountInCart": 1
}

###
# Удаление продукта из корзины у клиента
DELETE localhost:8080/users/1/cart/products/2

###
# Удаление всех продуктов из корзины у клиента
DELETE localhost:8080/users/1/cart/products


###
# Оплата корзины клиента по номеру банк. карты
PUT localhost:8080/users/1/cart/payment
Content-Type: application/json

{
  "cardNumber": "1111 2222 3333 4444"
}
